### PR TITLE
Allow repos with dashes

### PR DESCRIPTION
**Pull request by valgogo**

### CODE REVIEW

**Comment by valgogo** [comment]
@jacobaweiss

**Comment by jacobaweiss** [comment]
looks cool, though I'm not sure if repos can have `.`s or `/`s in their names? not gonna hurt to allow it tho.

**Comment by jacobaweiss** [comment]
testing @jacobaweiss

**Comment by valgogo** [comment]
@jacobaweiss you're correct about the `/`s, however `.` is allowed. The allowed characters are `[A-Za-z0-9_.-]`[1](https://github.com/docker/docker/issues/679#issuecomment-18307522)

Is it worth fixing this?

**Comment by jacobaweiss** [comment]
nah, its fine

**Comment by valgogo** [comment]
image

**Pull request merged**
